name: Release Extension

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5
      - name: Build Zip
        run: ./gradlew hivemqExtensionZip
      - name: Generate SHA256 checksum
        run: |
          cd build/hivemq-extension
          sha256sum hivemq-allow-all-extension-${{ github.event.release.name }}.zip | cut -d' ' -f1 > hivemq-allow-all-extension-${{ github.event.release.name }}.sha256
      - name: Upload Release Asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/hivemq-extension/hivemq-allow-all-extension-${{ github.event.release.name }}.zip
          asset_name: hivemq-allow-all-extension-${{ github.event.release.name }}.zip
          asset_content_type: application/zip
      - name: Upload SHA256 Checksum
        run: gh release upload ${{ github.event.release.tag_name }} ./build/hivemq-extension/hivemq-allow-all-extension-${{ github.event.release.name }}.sha256
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
